# Generated by Django 5.0.3 on 2024-03-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotresponse',
            old_name='user_id',
            new_name='user',
        ),
    ]
