# Generated by Django 5.0.3 on 2024-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_user_id_chatbotresponse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotresponse',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
