# Generated by Django 5.0.3 on 2024-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_chatbotresponse_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotresponse',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
