# Generated by Django 5.0.3 on 2024-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_chatbotresponse_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreDefineQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
    ]
