# Generated by Django 5.0.3 on 2024-04-02 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_chatresponses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('medical_conditions', models.CharField(max_length=255)),
                ('physical_activity', models.CharField(max_length=255)),
                ('diet', models.CharField(max_length=255)),
                ('sleep', models.CharField(max_length=255)),
                ('stress_levels', models.CharField(max_length=255)),
                ('habits', models.CharField(max_length=255)),
                ('family_history', models.CharField(max_length=255)),
                ('health_goals', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
