# Generated by Django 5.0.3 on 2024-04-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_userresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='stress_levels',
            new_name='stress',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='sleep',
        ),
    ]
