# Generated by Django 5.0.3 on 2024-04-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_stress_levels_userresponse_stress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='PreDefineQA',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatBotResponse',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
